# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: mjpritchard/sv-test-ceda-div

slug:
  encoding: unicode
  clean-accents: true
  sanitize-replacement: '-'
  lowercase: true

media_folder: /assets/img
public_folder: /img

#site_url: localhost:1313

#tag_options:
#  - news
#  - jasmin
#  - ceda
#  - data-incident-nov25


collections:
  - name: news
    label: News updates
    label_singular: News update
    folder: /content/news/updates
    path: '{{year}}/{{slug}}'
    summary: "{{date | date('YYYY-MM-DD')}} {{title}}"
    media_folder: '{{media_folder}}/news'
    public_folder: '{{public_folder}}/news'
    fields:
      - { label: Date, name: date, widget: datetime }
      - { 
        label: Tags,
        name: tags,
        widget: select,
        required: false,
        multiple: true,
        options: [
          'news',
          'ceda',
          'jasmin',
          'data-incident-nov25'
        ]
        }
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: markdown }
      - { label: Icon, name: icon, widget: string, required: false}
      - {
        label: Thumbnail,
        name: thumbnail, 
        widget: image,
        required: false
        }
          
    format: yaml-frontmatter
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
      